-- Order-to-cash: shipments, invoices, payments — Implementation Pack 1 §7.
-- Shipment quantities cannot exceed ordered (minus already-shipped); issuing an
-- invoice freezes its line amounts and its PDF is generated by a river job;
-- a captured payment >= invoice total flips it to paid.

CREATE TABLE shipments (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id       UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  order_id        BIGINT NOT NULL REFERENCES orders(id),
  carrier         text,
  tracking_number text,
  status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','shipped','delivered','returned')),
  shipped_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_shipments_order ON shipments(order_id);
CREATE TRIGGER trg_shipments_updated BEFORE UPDATE ON shipments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE shipment_items (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  shipment_id   BIGINT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
  order_item_id BIGINT NOT NULL REFERENCES order_items(id),
  quantity      NUMERIC(15,4) NOT NULL
);
CREATE INDEX idx_shipment_items_shipment ON shipment_items(shipment_id);
CREATE INDEX idx_shipment_items_order_item ON shipment_items(order_item_id);

CREATE TABLE invoices (
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id    UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  order_id     BIGINT NOT NULL REFERENCES orders(id),
  customer_id  BIGINT NOT NULL REFERENCES customers(id),
  status       text NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft','issued','paid','overdue','void')),
  currency     CHAR(3) NOT NULL,
  subtotal     NUMERIC(15,4) NOT NULL DEFAULT 0,
  tax_total    NUMERIC(15,4) NOT NULL DEFAULT 0,
  grand_total  NUMERIC(15,4) NOT NULL DEFAULT 0,
  issued_at    timestamptz,
  due_at       timestamptz,
  pdf_url      text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_invoices_customer ON invoices(customer_id);
CREATE INDEX idx_invoices_order ON invoices(order_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE TRIGGER trg_invoices_updated BEFORE UPDATE ON invoices
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE invoice_items (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  invoice_id  BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  description text NOT NULL,
  quantity    NUMERIC(15,4) NOT NULL,
  unit_price  NUMERIC(15,4) NOT NULL,
  tax_amount  NUMERIC(15,4) NOT NULL DEFAULT 0,
  row_total   NUMERIC(15,4) NOT NULL
);
CREATE INDEX idx_invoice_items_invoice ON invoice_items(invoice_id);

CREATE TABLE payments (
  id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id         UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  invoice_id        BIGINT REFERENCES invoices(id),
  order_id          BIGINT REFERENCES orders(id),
  customer_id       BIGINT NOT NULL REFERENCES customers(id),
  method            text NOT NULL CHECK (method IN ('card','ach','invoice','po','mpesa')),
  gateway           text,
  gateway_reference text,
  amount            NUMERIC(15,4) NOT NULL,
  currency          CHAR(3) NOT NULL,
  status            text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','authorized','captured','failed','refunded')),
  captured_at       timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_invoice ON payments(invoice_id);
CREATE INDEX idx_payments_customer ON payments(customer_id);
CREATE TRIGGER trg_payments_updated BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Order-to-cash permissions for the demo admin role.
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission
  FROM roles r
  CROSS JOIN (VALUES
    ('shipment.view'), ('shipment.manage'),
    ('invoice.view'), ('invoice.manage'),
    ('payment.view'), ('payment.manage')
  ) AS p(permission)
 WHERE r.organization_id = 1 AND r.name = 'admin'
ON CONFLICT DO NOTHING;
